apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: rakeshnexturn/cloud-native-monitoring-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"

