apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']  # Prometheus self-scraping

      - job_name: 'python-app'
        static_configs:
          - targets: ['python-app:80']  # Replace with your Python Flask app service name and port

